#define OPENSPACE_PASSABILITY_BLOCKED 1
#define OPENSPACE_PASSABILITY_TABLE 2
#define OPENSPACE_PASSABILITY_GANGWAY 4
#define OPENSPACE_PASSABILITY_PIPE_ATMOSPHERICS 8
#define OPENSPACE_PASSABILITY_PIPE_DISPOSAL 16
#define OPENSPACE_PASSABILITY_BLOCKED_DIRECTIONAL 32 // after this come direction flags